<?php
/**
 * CharacterMultiFightResultSchema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;

use \ArrayAccess;
use \ArtifactsMmo\ObjectSerializer;

/**
 * CharacterMultiFightResultSchema Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CharacterMultiFightResultSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CharacterMultiFightResultSchema';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'characterName' => 'string',
        'xp' => 'int',
        'gold' => 'int',
        'drops' => '\ArtifactsMmo\Model\DropSchema[]',
        'finalHp' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'characterName' => null,
        'xp' => null,
        'gold' => null,
        'drops' => null,
        'finalHp' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'characterName' => false,
        'xp' => false,
        'gold' => false,
        'drops' => false,
        'finalHp' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'characterName' => 'character_name',
        'xp' => 'xp',
        'gold' => 'gold',
        'drops' => 'drops',
        'finalHp' => 'final_hp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'characterName' => 'setCharacterName',
        'xp' => 'setXp',
        'gold' => 'setGold',
        'drops' => 'setDrops',
        'finalHp' => 'setFinalHp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'characterName' => 'getCharacterName',
        'xp' => 'getXp',
        'gold' => 'getGold',
        'drops' => 'getDrops',
        'finalHp' => 'getFinalHp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('characterName', $data ?? [], null);
        $this->setIfExists('xp', $data ?? [], null);
        $this->setIfExists('gold', $data ?? [], null);
        $this->setIfExists('drops', $data ?? [], null);
        $this->setIfExists('finalHp', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['characterName'] === null) {
            $invalidProperties[] = "'characterName' can't be null";
        }
        if ($this->container['xp'] === null) {
            $invalidProperties[] = "'xp' can't be null";
        }
        if ($this->container['gold'] === null) {
            $invalidProperties[] = "'gold' can't be null";
        }
        if ($this->container['drops'] === null) {
            $invalidProperties[] = "'drops' can't be null";
        }
        if ($this->container['finalHp'] === null) {
            $invalidProperties[] = "'finalHp' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets characterName
     *
     * @return string
     */
    public function getCharacterName()
    {
        return $this->container['characterName'];
    }

    /**
     * Sets characterName
     *
     * @param string $characterName Name of the character.
     *
     * @return self
     */
    public function setCharacterName($characterName)
    {
        if (is_null($characterName)) {
            throw new \InvalidArgumentException('non-nullable characterName cannot be null');
        }
        $this->container['characterName'] = $characterName;

        return $this;
    }

    /**
     * Gets xp
     *
     * @return int
     */
    public function getXp()
    {
        return $this->container['xp'];
    }

    /**
     * Sets xp
     *
     * @param int $xp XP gained by this character.
     *
     * @return self
     */
    public function setXp($xp)
    {
        if (is_null($xp)) {
            throw new \InvalidArgumentException('non-nullable xp cannot be null');
        }
        $this->container['xp'] = $xp;

        return $this;
    }

    /**
     * Gets gold
     *
     * @return int
     */
    public function getGold()
    {
        return $this->container['gold'];
    }

    /**
     * Sets gold
     *
     * @param int $gold Gold gained by this character.
     *
     * @return self
     */
    public function setGold($gold)
    {
        if (is_null($gold)) {
            throw new \InvalidArgumentException('non-nullable gold cannot be null');
        }
        $this->container['gold'] = $gold;

        return $this;
    }

    /**
     * Gets drops
     *
     * @return \ArtifactsMmo\Model\DropSchema[]
     */
    public function getDrops()
    {
        return $this->container['drops'];
    }

    /**
     * Sets drops
     *
     * @param \ArtifactsMmo\Model\DropSchema[] $drops Items dropped for this character.
     *
     * @return self
     */
    public function setDrops($drops)
    {
        if (is_null($drops)) {
            throw new \InvalidArgumentException('non-nullable drops cannot be null');
        }
        $this->container['drops'] = $drops;

        return $this;
    }

    /**
     * Gets finalHp
     *
     * @return int
     */
    public function getFinalHp()
    {
        return $this->container['finalHp'];
    }

    /**
     * Sets finalHp
     *
     * @param int $finalHp Character's HP at the end of combat.
     *
     * @return self
     */
    public function setFinalHp($finalHp)
    {
        if (is_null($finalHp)) {
            throw new \InvalidArgumentException('non-nullable finalHp cannot be null');
        }
        $this->container['finalHp'] = $finalHp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


