<?php
/**
 * EventSchema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;

use \ArrayAccess;
use \ArtifactsMmo\ObjectSerializer;

/**
 * EventSchema Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EventSchema';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'code' => 'string',
        'content' => '\ArtifactsMmo\Model\EventContentSchema',
        'maps' => '\ArtifactsMmo\Model\EventMapSchema[]',
        'duration' => 'int',
        'rate' => 'int',
        'cooldown' => 'int',
        'price' => 'int',
        'transition' => '\ArtifactsMmo\Model\TransitionSchema',
        'cooldownExpiration' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'code' => null,
        'content' => null,
        'maps' => null,
        'duration' => null,
        'rate' => null,
        'cooldown' => null,
        'price' => null,
        'transition' => null,
        'cooldownExpiration' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'code' => false,
        'content' => false,
        'maps' => false,
        'duration' => false,
        'rate' => false,
        'cooldown' => false,
        'price' => false,
        'transition' => false,
        'cooldownExpiration' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'code' => 'code',
        'content' => 'content',
        'maps' => 'maps',
        'duration' => 'duration',
        'rate' => 'rate',
        'cooldown' => 'cooldown',
        'price' => 'price',
        'transition' => 'transition',
        'cooldownExpiration' => 'cooldown_expiration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'code' => 'setCode',
        'content' => 'setContent',
        'maps' => 'setMaps',
        'duration' => 'setDuration',
        'rate' => 'setRate',
        'cooldown' => 'setCooldown',
        'price' => 'setPrice',
        'transition' => 'setTransition',
        'cooldownExpiration' => 'setCooldownExpiration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'code' => 'getCode',
        'content' => 'getContent',
        'maps' => 'getMaps',
        'duration' => 'getDuration',
        'rate' => 'getRate',
        'cooldown' => 'getCooldown',
        'price' => 'getPrice',
        'transition' => 'getTransition',
        'cooldownExpiration' => 'getCooldownExpiration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('maps', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('rate', $data ?? [], null);
        $this->setIfExists('cooldown', $data ?? [], 0);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('transition', $data ?? [], null);
        $this->setIfExists('cooldownExpiration', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['maps'] === null) {
            $invalidProperties[] = "'maps' can't be null";
        }
        if ($this->container['duration'] === null) {
            $invalidProperties[] = "'duration' can't be null";
        }
        if ($this->container['rate'] === null) {
            $invalidProperties[] = "'rate' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the event.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code Code of the event.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets content
     *
     * @return \ArtifactsMmo\Model\EventContentSchema|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param \ArtifactsMmo\Model\EventContentSchema|null $content Content of the event.
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets maps
     *
     * @return \ArtifactsMmo\Model\EventMapSchema[]
     */
    public function getMaps()
    {
        return $this->container['maps'];
    }

    /**
     * Sets maps
     *
     * @param \ArtifactsMmo\Model\EventMapSchema[] $maps Map list of the event.
     *
     * @return self
     */
    public function setMaps($maps)
    {
        if (is_null($maps)) {
            throw new \InvalidArgumentException('non-nullable maps cannot be null');
        }
        $this->container['maps'] = $maps;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return int
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param int $duration Duration in minutes.
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            throw new \InvalidArgumentException('non-nullable duration cannot be null');
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return int
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param int $rate Rate spawn of the event. (1/rate every minute)
     *
     * @return self
     */
    public function setRate($rate)
    {
        if (is_null($rate)) {
            throw new \InvalidArgumentException('non-nullable rate cannot be null');
        }
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets cooldown
     *
     * @return int|null
     */
    public function getCooldown()
    {
        return $this->container['cooldown'];
    }

    /**
     * Sets cooldown
     *
     * @param int|null $cooldown Cooldown in minutes before the event can be spawned with gems.
     *
     * @return self
     */
    public function setCooldown($cooldown)
    {
        if (is_null($cooldown)) {
            throw new \InvalidArgumentException('non-nullable cooldown cannot be null');
        }
        $this->container['cooldown'] = $cooldown;

        return $this;
    }

    /**
     * Gets price
     *
     * @return int|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param int|null $price Price in gems to spawn the event. Null if not purchasable.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets transition
     *
     * @return \ArtifactsMmo\Model\TransitionSchema|null
     */
    public function getTransition()
    {
        return $this->container['transition'];
    }

    /**
     * Sets transition
     *
     * @param \ArtifactsMmo\Model\TransitionSchema|null $transition Transition to add to the map when event is active.
     *
     * @return self
     */
    public function setTransition($transition)
    {
        if (is_null($transition)) {
            throw new \InvalidArgumentException('non-nullable transition cannot be null');
        }
        $this->container['transition'] = $transition;

        return $this;
    }

    /**
     * Gets cooldownExpiration
     *
     * @return \DateTime|null
     */
    public function getCooldownExpiration()
    {
        return $this->container['cooldownExpiration'];
    }

    /**
     * Sets cooldownExpiration
     *
     * @param \DateTime|null $cooldownExpiration Gems spawn cooldown expiration datetime (null if not on cooldown).
     *
     * @return self
     */
    public function setCooldownExpiration($cooldownExpiration)
    {
        if (is_null($cooldownExpiration)) {
            throw new \InvalidArgumentException('non-nullable cooldownExpiration cannot be null');
        }
        $this->container['cooldownExpiration'] = $cooldownExpiration;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


