<?php
/**
 * ItemType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;
use \ArtifactsMmo\ObjectSerializer;

/**
 * ItemType Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemType
{
    /**
     * Possible values of this enum
     */
    public const UTILITY = 'utility';

    public const BODY_ARMOR = 'body_armor';

    public const WEAPON = 'weapon';

    public const RESOURCE = 'resource';

    public const LEG_ARMOR = 'leg_armor';

    public const HELMET = 'helmet';

    public const BOOTS = 'boots';

    public const SHIELD = 'shield';

    public const AMULET = 'amulet';

    public const RING = 'ring';

    public const ARTIFACT = 'artifact';

    public const CURRENCY = 'currency';

    public const CONSUMABLE = 'consumable';

    public const RUNE = 'rune';

    public const BAG = 'bag';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UTILITY,
            self::BODY_ARMOR,
            self::WEAPON,
            self::RESOURCE,
            self::LEG_ARMOR,
            self::HELMET,
            self::BOOTS,
            self::SHIELD,
            self::AMULET,
            self::RING,
            self::ARTIFACT,
            self::CURRENCY,
            self::CONSUMABLE,
            self::RUNE,
            self::BAG
        ];
    }
}


