<?php
/**
 * MapContentType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;
use \ArtifactsMmo\ObjectSerializer;

/**
 * MapContentType Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MapContentType
{
    /**
     * Possible values of this enum
     */
    public const MONSTER = 'monster';

    public const RESOURCE = 'resource';

    public const WORKSHOP = 'workshop';

    public const BANK = 'bank';

    public const GRAND_EXCHANGE = 'grand_exchange';

    public const TASKS_MASTER = 'tasks_master';

    public const NPC = 'npc';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MONSTER,
            self::RESOURCE,
            self::WORKSHOP,
            self::BANK,
            self::GRAND_EXCHANGE,
            self::TASKS_MASTER,
            self::NPC
        ];
    }
}


