<?php
/**
 * MonsterSchema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;

use \ArrayAccess;
use \ArtifactsMmo\ObjectSerializer;

/**
 * MonsterSchema Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MonsterSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MonsterSchema';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'code' => 'string',
        'level' => 'int',
        'type' => '\ArtifactsMmo\Model\MonsterType',
        'hp' => 'int',
        'attackFire' => 'int',
        'attackEarth' => 'int',
        'attackWater' => 'int',
        'attackAir' => 'int',
        'resFire' => 'int',
        'resEarth' => 'int',
        'resWater' => 'int',
        'resAir' => 'int',
        'criticalStrike' => 'int',
        'initiative' => 'int',
        'effects' => '\ArtifactsMmo\Model\SimpleEffectSchema[]',
        'minGold' => 'int',
        'maxGold' => 'int',
        'drops' => '\ArtifactsMmo\Model\DropRateSchema[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'code' => null,
        'level' => null,
        'type' => null,
        'hp' => null,
        'attackFire' => null,
        'attackEarth' => null,
        'attackWater' => null,
        'attackAir' => null,
        'resFire' => null,
        'resEarth' => null,
        'resWater' => null,
        'resAir' => null,
        'criticalStrike' => null,
        'initiative' => null,
        'effects' => null,
        'minGold' => null,
        'maxGold' => null,
        'drops' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'code' => false,
        'level' => false,
        'type' => false,
        'hp' => false,
        'attackFire' => false,
        'attackEarth' => false,
        'attackWater' => false,
        'attackAir' => false,
        'resFire' => false,
        'resEarth' => false,
        'resWater' => false,
        'resAir' => false,
        'criticalStrike' => false,
        'initiative' => false,
        'effects' => false,
        'minGold' => false,
        'maxGold' => false,
        'drops' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'code' => 'code',
        'level' => 'level',
        'type' => 'type',
        'hp' => 'hp',
        'attackFire' => 'attack_fire',
        'attackEarth' => 'attack_earth',
        'attackWater' => 'attack_water',
        'attackAir' => 'attack_air',
        'resFire' => 'res_fire',
        'resEarth' => 'res_earth',
        'resWater' => 'res_water',
        'resAir' => 'res_air',
        'criticalStrike' => 'critical_strike',
        'initiative' => 'initiative',
        'effects' => 'effects',
        'minGold' => 'min_gold',
        'maxGold' => 'max_gold',
        'drops' => 'drops'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'code' => 'setCode',
        'level' => 'setLevel',
        'type' => 'setType',
        'hp' => 'setHp',
        'attackFire' => 'setAttackFire',
        'attackEarth' => 'setAttackEarth',
        'attackWater' => 'setAttackWater',
        'attackAir' => 'setAttackAir',
        'resFire' => 'setResFire',
        'resEarth' => 'setResEarth',
        'resWater' => 'setResWater',
        'resAir' => 'setResAir',
        'criticalStrike' => 'setCriticalStrike',
        'initiative' => 'setInitiative',
        'effects' => 'setEffects',
        'minGold' => 'setMinGold',
        'maxGold' => 'setMaxGold',
        'drops' => 'setDrops'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'code' => 'getCode',
        'level' => 'getLevel',
        'type' => 'getType',
        'hp' => 'getHp',
        'attackFire' => 'getAttackFire',
        'attackEarth' => 'getAttackEarth',
        'attackWater' => 'getAttackWater',
        'attackAir' => 'getAttackAir',
        'resFire' => 'getResFire',
        'resEarth' => 'getResEarth',
        'resWater' => 'getResWater',
        'resAir' => 'getResAir',
        'criticalStrike' => 'getCriticalStrike',
        'initiative' => 'getInitiative',
        'effects' => 'getEffects',
        'minGold' => 'getMinGold',
        'maxGold' => 'getMaxGold',
        'drops' => 'getDrops'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('hp', $data ?? [], null);
        $this->setIfExists('attackFire', $data ?? [], null);
        $this->setIfExists('attackEarth', $data ?? [], null);
        $this->setIfExists('attackWater', $data ?? [], null);
        $this->setIfExists('attackAir', $data ?? [], null);
        $this->setIfExists('resFire', $data ?? [], null);
        $this->setIfExists('resEarth', $data ?? [], null);
        $this->setIfExists('resWater', $data ?? [], null);
        $this->setIfExists('resAir', $data ?? [], null);
        $this->setIfExists('criticalStrike', $data ?? [], null);
        $this->setIfExists('initiative', $data ?? [], null);
        $this->setIfExists('effects', $data ?? [], null);
        $this->setIfExists('minGold', $data ?? [], null);
        $this->setIfExists('maxGold', $data ?? [], null);
        $this->setIfExists('drops', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['level'] === null) {
            $invalidProperties[] = "'level' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['hp'] === null) {
            $invalidProperties[] = "'hp' can't be null";
        }
        if ($this->container['attackFire'] === null) {
            $invalidProperties[] = "'attackFire' can't be null";
        }
        if ($this->container['attackEarth'] === null) {
            $invalidProperties[] = "'attackEarth' can't be null";
        }
        if ($this->container['attackWater'] === null) {
            $invalidProperties[] = "'attackWater' can't be null";
        }
        if ($this->container['attackAir'] === null) {
            $invalidProperties[] = "'attackAir' can't be null";
        }
        if ($this->container['resFire'] === null) {
            $invalidProperties[] = "'resFire' can't be null";
        }
        if ($this->container['resEarth'] === null) {
            $invalidProperties[] = "'resEarth' can't be null";
        }
        if ($this->container['resWater'] === null) {
            $invalidProperties[] = "'resWater' can't be null";
        }
        if ($this->container['resAir'] === null) {
            $invalidProperties[] = "'resAir' can't be null";
        }
        if ($this->container['criticalStrike'] === null) {
            $invalidProperties[] = "'criticalStrike' can't be null";
        }
        if ($this->container['initiative'] === null) {
            $invalidProperties[] = "'initiative' can't be null";
        }
        if ($this->container['minGold'] === null) {
            $invalidProperties[] = "'minGold' can't be null";
        }
        if ($this->container['maxGold'] === null) {
            $invalidProperties[] = "'maxGold' can't be null";
        }
        if ($this->container['drops'] === null) {
            $invalidProperties[] = "'drops' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the monster.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code The code of the monster. This is the monster's unique identifier (ID).
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int
     */
    public function getLevel()
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int $level Monster level.
     *
     * @return self
     */
    public function setLevel($level)
    {
        if (is_null($level)) {
            throw new \InvalidArgumentException('non-nullable level cannot be null');
        }
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \ArtifactsMmo\Model\MonsterType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \ArtifactsMmo\Model\MonsterType $type Monster type.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets hp
     *
     * @return int
     */
    public function getHp()
    {
        return $this->container['hp'];
    }

    /**
     * Sets hp
     *
     * @param int $hp Monster hit points.
     *
     * @return self
     */
    public function setHp($hp)
    {
        if (is_null($hp)) {
            throw new \InvalidArgumentException('non-nullable hp cannot be null');
        }
        $this->container['hp'] = $hp;

        return $this;
    }

    /**
     * Gets attackFire
     *
     * @return int
     */
    public function getAttackFire()
    {
        return $this->container['attackFire'];
    }

    /**
     * Sets attackFire
     *
     * @param int $attackFire Monster fire attack.
     *
     * @return self
     */
    public function setAttackFire($attackFire)
    {
        if (is_null($attackFire)) {
            throw new \InvalidArgumentException('non-nullable attackFire cannot be null');
        }
        $this->container['attackFire'] = $attackFire;

        return $this;
    }

    /**
     * Gets attackEarth
     *
     * @return int
     */
    public function getAttackEarth()
    {
        return $this->container['attackEarth'];
    }

    /**
     * Sets attackEarth
     *
     * @param int $attackEarth Monster earth attack.
     *
     * @return self
     */
    public function setAttackEarth($attackEarth)
    {
        if (is_null($attackEarth)) {
            throw new \InvalidArgumentException('non-nullable attackEarth cannot be null');
        }
        $this->container['attackEarth'] = $attackEarth;

        return $this;
    }

    /**
     * Gets attackWater
     *
     * @return int
     */
    public function getAttackWater()
    {
        return $this->container['attackWater'];
    }

    /**
     * Sets attackWater
     *
     * @param int $attackWater Monster water attack.
     *
     * @return self
     */
    public function setAttackWater($attackWater)
    {
        if (is_null($attackWater)) {
            throw new \InvalidArgumentException('non-nullable attackWater cannot be null');
        }
        $this->container['attackWater'] = $attackWater;

        return $this;
    }

    /**
     * Gets attackAir
     *
     * @return int
     */
    public function getAttackAir()
    {
        return $this->container['attackAir'];
    }

    /**
     * Sets attackAir
     *
     * @param int $attackAir Monster air attack.
     *
     * @return self
     */
    public function setAttackAir($attackAir)
    {
        if (is_null($attackAir)) {
            throw new \InvalidArgumentException('non-nullable attackAir cannot be null');
        }
        $this->container['attackAir'] = $attackAir;

        return $this;
    }

    /**
     * Gets resFire
     *
     * @return int
     */
    public function getResFire()
    {
        return $this->container['resFire'];
    }

    /**
     * Sets resFire
     *
     * @param int $resFire Monster % fire resistance.
     *
     * @return self
     */
    public function setResFire($resFire)
    {
        if (is_null($resFire)) {
            throw new \InvalidArgumentException('non-nullable resFire cannot be null');
        }
        $this->container['resFire'] = $resFire;

        return $this;
    }

    /**
     * Gets resEarth
     *
     * @return int
     */
    public function getResEarth()
    {
        return $this->container['resEarth'];
    }

    /**
     * Sets resEarth
     *
     * @param int $resEarth Monster % earth resistance.
     *
     * @return self
     */
    public function setResEarth($resEarth)
    {
        if (is_null($resEarth)) {
            throw new \InvalidArgumentException('non-nullable resEarth cannot be null');
        }
        $this->container['resEarth'] = $resEarth;

        return $this;
    }

    /**
     * Gets resWater
     *
     * @return int
     */
    public function getResWater()
    {
        return $this->container['resWater'];
    }

    /**
     * Sets resWater
     *
     * @param int $resWater Monster % water resistance.
     *
     * @return self
     */
    public function setResWater($resWater)
    {
        if (is_null($resWater)) {
            throw new \InvalidArgumentException('non-nullable resWater cannot be null');
        }
        $this->container['resWater'] = $resWater;

        return $this;
    }

    /**
     * Gets resAir
     *
     * @return int
     */
    public function getResAir()
    {
        return $this->container['resAir'];
    }

    /**
     * Sets resAir
     *
     * @param int $resAir Monster % air resistance.
     *
     * @return self
     */
    public function setResAir($resAir)
    {
        if (is_null($resAir)) {
            throw new \InvalidArgumentException('non-nullable resAir cannot be null');
        }
        $this->container['resAir'] = $resAir;

        return $this;
    }

    /**
     * Gets criticalStrike
     *
     * @return int
     */
    public function getCriticalStrike()
    {
        return $this->container['criticalStrike'];
    }

    /**
     * Sets criticalStrike
     *
     * @param int $criticalStrike Monster % critical strike.
     *
     * @return self
     */
    public function setCriticalStrike($criticalStrike)
    {
        if (is_null($criticalStrike)) {
            throw new \InvalidArgumentException('non-nullable criticalStrike cannot be null');
        }
        $this->container['criticalStrike'] = $criticalStrike;

        return $this;
    }

    /**
     * Gets initiative
     *
     * @return int
     */
    public function getInitiative()
    {
        return $this->container['initiative'];
    }

    /**
     * Sets initiative
     *
     * @param int $initiative Monster initiative for turn order.
     *
     * @return self
     */
    public function setInitiative($initiative)
    {
        if (is_null($initiative)) {
            throw new \InvalidArgumentException('non-nullable initiative cannot be null');
        }
        $this->container['initiative'] = $initiative;

        return $this;
    }

    /**
     * Gets effects
     *
     * @return \ArtifactsMmo\Model\SimpleEffectSchema[]|null
     */
    public function getEffects()
    {
        return $this->container['effects'];
    }

    /**
     * Sets effects
     *
     * @param \ArtifactsMmo\Model\SimpleEffectSchema[]|null $effects List of effects.
     *
     * @return self
     */
    public function setEffects($effects)
    {
        if (is_null($effects)) {
            throw new \InvalidArgumentException('non-nullable effects cannot be null');
        }
        $this->container['effects'] = $effects;

        return $this;
    }

    /**
     * Gets minGold
     *
     * @return int
     */
    public function getMinGold()
    {
        return $this->container['minGold'];
    }

    /**
     * Sets minGold
     *
     * @param int $minGold Monster minimum gold drop.
     *
     * @return self
     */
    public function setMinGold($minGold)
    {
        if (is_null($minGold)) {
            throw new \InvalidArgumentException('non-nullable minGold cannot be null');
        }
        $this->container['minGold'] = $minGold;

        return $this;
    }

    /**
     * Gets maxGold
     *
     * @return int
     */
    public function getMaxGold()
    {
        return $this->container['maxGold'];
    }

    /**
     * Sets maxGold
     *
     * @param int $maxGold Monster maximum gold drop.
     *
     * @return self
     */
    public function setMaxGold($maxGold)
    {
        if (is_null($maxGold)) {
            throw new \InvalidArgumentException('non-nullable maxGold cannot be null');
        }
        $this->container['maxGold'] = $maxGold;

        return $this;
    }

    /**
     * Gets drops
     *
     * @return \ArtifactsMmo\Model\DropRateSchema[]
     */
    public function getDrops()
    {
        return $this->container['drops'];
    }

    /**
     * Sets drops
     *
     * @param \ArtifactsMmo\Model\DropRateSchema[] $drops Monster drops. This is a list of items that the monster drops after killing the monster.
     *
     * @return self
     */
    public function setDrops($drops)
    {
        if (is_null($drops)) {
            throw new \InvalidArgumentException('non-nullable drops cannot be null');
        }
        $this->container['drops'] = $drops;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


