<?php
/**
 * RaidScheduleSchema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;

use \ArrayAccess;
use \ArtifactsMmo\ObjectSerializer;

/**
 * RaidScheduleSchema Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RaidScheduleSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RaidScheduleSchema';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'weekdays' => '\ArtifactsMmo\Model\RaidWeekday[]',
        'startHourUtc' => 'int',
        'startMinuteUtc' => 'int',
        'durationHours' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'weekdays' => null,
        'startHourUtc' => null,
        'startMinuteUtc' => null,
        'durationHours' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'weekdays' => false,
        'startHourUtc' => false,
        'startMinuteUtc' => false,
        'durationHours' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'weekdays' => 'weekdays',
        'startHourUtc' => 'start_hour_utc',
        'startMinuteUtc' => 'start_minute_utc',
        'durationHours' => 'duration_hours'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'weekdays' => 'setWeekdays',
        'startHourUtc' => 'setStartHourUtc',
        'startMinuteUtc' => 'setStartMinuteUtc',
        'durationHours' => 'setDurationHours'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'weekdays' => 'getWeekdays',
        'startHourUtc' => 'getStartHourUtc',
        'startMinuteUtc' => 'getStartMinuteUtc',
        'durationHours' => 'getDurationHours'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('weekdays', $data ?? [], null);
        $this->setIfExists('startHourUtc', $data ?? [], 0);
        $this->setIfExists('startMinuteUtc', $data ?? [], 0);
        $this->setIfExists('durationHours', $data ?? [], 24);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['weekdays'] === null) {
            $invalidProperties[] = "'weekdays' can't be null";
        }
        if ((count($this->container['weekdays']) < 1)) {
            $invalidProperties[] = "invalid value for 'weekdays', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['startHourUtc']) && ($this->container['startHourUtc'] > 23)) {
            $invalidProperties[] = "invalid value for 'startHourUtc', must be smaller than or equal to 23.";
        }

        if (!is_null($this->container['startHourUtc']) && ($this->container['startHourUtc'] < 0)) {
            $invalidProperties[] = "invalid value for 'startHourUtc', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['startMinuteUtc']) && ($this->container['startMinuteUtc'] > 59)) {
            $invalidProperties[] = "invalid value for 'startMinuteUtc', must be smaller than or equal to 59.";
        }

        if (!is_null($this->container['startMinuteUtc']) && ($this->container['startMinuteUtc'] < 0)) {
            $invalidProperties[] = "invalid value for 'startMinuteUtc', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['durationHours']) && ($this->container['durationHours'] > 168)) {
            $invalidProperties[] = "invalid value for 'durationHours', must be smaller than or equal to 168.";
        }

        if (!is_null($this->container['durationHours']) && ($this->container['durationHours'] < 1)) {
            $invalidProperties[] = "invalid value for 'durationHours', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets weekdays
     *
     * @return \ArtifactsMmo\Model\RaidWeekday[]
     */
    public function getWeekdays()
    {
        return $this->container['weekdays'];
    }

    /**
     * Sets weekdays
     *
     * @param \ArtifactsMmo\Model\RaidWeekday[] $weekdays UTC weekdays when the raid opens.
     *
     * @return self
     */
    public function setWeekdays($weekdays)
    {
        if (is_null($weekdays)) {
            throw new \InvalidArgumentException('non-nullable weekdays cannot be null');
        }


        if ((count($weekdays) < 1)) {
            throw new \InvalidArgumentException('invalid length for $weekdays when calling RaidScheduleSchema., number of items must be greater than or equal to 1.');
        }
        $this->container['weekdays'] = $weekdays;

        return $this;
    }

    /**
     * Gets startHourUtc
     *
     * @return int|null
     */
    public function getStartHourUtc()
    {
        return $this->container['startHourUtc'];
    }

    /**
     * Sets startHourUtc
     *
     * @param int|null $startHourUtc UTC hour when the raid opens.
     *
     * @return self
     */
    public function setStartHourUtc($startHourUtc)
    {
        if (is_null($startHourUtc)) {
            throw new \InvalidArgumentException('non-nullable startHourUtc cannot be null');
        }

        if (($startHourUtc > 23)) {
            throw new \InvalidArgumentException('invalid value for $startHourUtc when calling RaidScheduleSchema., must be smaller than or equal to 23.');
        }
        if (($startHourUtc < 0)) {
            throw new \InvalidArgumentException('invalid value for $startHourUtc when calling RaidScheduleSchema., must be bigger than or equal to 0.');
        }

        $this->container['startHourUtc'] = $startHourUtc;

        return $this;
    }

    /**
     * Gets startMinuteUtc
     *
     * @return int|null
     */
    public function getStartMinuteUtc()
    {
        return $this->container['startMinuteUtc'];
    }

    /**
     * Sets startMinuteUtc
     *
     * @param int|null $startMinuteUtc UTC minute when the raid opens.
     *
     * @return self
     */
    public function setStartMinuteUtc($startMinuteUtc)
    {
        if (is_null($startMinuteUtc)) {
            throw new \InvalidArgumentException('non-nullable startMinuteUtc cannot be null');
        }

        if (($startMinuteUtc > 59)) {
            throw new \InvalidArgumentException('invalid value for $startMinuteUtc when calling RaidScheduleSchema., must be smaller than or equal to 59.');
        }
        if (($startMinuteUtc < 0)) {
            throw new \InvalidArgumentException('invalid value for $startMinuteUtc when calling RaidScheduleSchema., must be bigger than or equal to 0.');
        }

        $this->container['startMinuteUtc'] = $startMinuteUtc;

        return $this;
    }

    /**
     * Gets durationHours
     *
     * @return int|null
     */
    public function getDurationHours()
    {
        return $this->container['durationHours'];
    }

    /**
     * Sets durationHours
     *
     * @param int|null $durationHours Maximum raid duration in hours.
     *
     * @return self
     */
    public function setDurationHours($durationHours)
    {
        if (is_null($durationHours)) {
            throw new \InvalidArgumentException('non-nullable durationHours cannot be null');
        }

        if (($durationHours > 168)) {
            throw new \InvalidArgumentException('invalid value for $durationHours when calling RaidScheduleSchema., must be smaller than or equal to 168.');
        }
        if (($durationHours < 1)) {
            throw new \InvalidArgumentException('invalid value for $durationHours when calling RaidScheduleSchema., must be bigger than or equal to 1.');
        }

        $this->container['durationHours'] = $durationHours;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


