<?php
/**
 * RaidStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;
use \ArtifactsMmo\ObjectSerializer;

/**
 * RaidStatus Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RaidStatus
{
    /**
     * Possible values of this enum
     */
    public const UPCOMING = 'upcoming';

    public const ACTIVE = 'active';

    public const FINISHED_SUCCESS = 'finished_success';

    public const FINISHED_FAILURE = 'finished_failure';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UPCOMING,
            self::ACTIVE,
            self::FINISHED_SUCCESS,
            self::FINISHED_FAILURE
        ];
    }
}


