<?php
/**
 * RaidSchema
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Model;

use \ArrayAccess;
use \ArtifactsMmo\ObjectSerializer;

/**
 * RaidSchema Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RaidSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RaidSchema';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'code' => 'string',
        'name' => 'string',
        'description' => 'string',
        'monster' => 'string',
        'schedule' => '\ArtifactsMmo\Model\RaidScheduleSchema',
        'rewards' => '\ArtifactsMmo\Model\RaidRewardsSchema',
        'status' => '\ArtifactsMmo\Model\RaidStatus',
        'nextStartAt' => '\DateTime',
        'participantCount' => 'int',
        'activeInstance' => '\ArtifactsMmo\Model\RaidInstanceSchema',
        'latestInstance' => '\ArtifactsMmo\Model\RaidInstanceSchema'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'code' => null,
        'name' => null,
        'description' => null,
        'monster' => null,
        'schedule' => null,
        'rewards' => null,
        'status' => null,
        'nextStartAt' => 'date-time',
        'participantCount' => null,
        'activeInstance' => null,
        'latestInstance' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'code' => false,
        'name' => false,
        'description' => false,
        'monster' => false,
        'schedule' => false,
        'rewards' => false,
        'status' => false,
        'nextStartAt' => false,
        'participantCount' => false,
        'activeInstance' => false,
        'latestInstance' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'name' => 'name',
        'description' => 'description',
        'monster' => 'monster',
        'schedule' => 'schedule',
        'rewards' => 'rewards',
        'status' => 'status',
        'nextStartAt' => 'next_start_at',
        'participantCount' => 'participant_count',
        'activeInstance' => 'active_instance',
        'latestInstance' => 'latest_instance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'name' => 'setName',
        'description' => 'setDescription',
        'monster' => 'setMonster',
        'schedule' => 'setSchedule',
        'rewards' => 'setRewards',
        'status' => 'setStatus',
        'nextStartAt' => 'setNextStartAt',
        'participantCount' => 'setParticipantCount',
        'activeInstance' => 'setActiveInstance',
        'latestInstance' => 'setLatestInstance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'name' => 'getName',
        'description' => 'getDescription',
        'monster' => 'getMonster',
        'schedule' => 'getSchedule',
        'rewards' => 'getRewards',
        'status' => 'getStatus',
        'nextStartAt' => 'getNextStartAt',
        'participantCount' => 'getParticipantCount',
        'activeInstance' => 'getActiveInstance',
        'latestInstance' => 'getLatestInstance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('monster', $data ?? [], null);
        $this->setIfExists('schedule', $data ?? [], null);
        $this->setIfExists('rewards', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('nextStartAt', $data ?? [], null);
        $this->setIfExists('participantCount', $data ?? [], 0);
        $this->setIfExists('activeInstance', $data ?? [], null);
        $this->setIfExists('latestInstance', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['monster'] === null) {
            $invalidProperties[] = "'monster' can't be null";
        }
        if ($this->container['schedule'] === null) {
            $invalidProperties[] = "'schedule' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['nextStartAt'] === null) {
            $invalidProperties[] = "'nextStartAt' can't be null";
        }
        if (!is_null($this->container['participantCount']) && ($this->container['participantCount'] < 0)) {
            $invalidProperties[] = "invalid value for 'participantCount', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code Raid code.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Raid name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Raid description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets monster
     *
     * @return string
     */
    public function getMonster()
    {
        return $this->container['monster'];
    }

    /**
     * Sets monster
     *
     * @param string $monster Monster code used for raid combat simulation.
     *
     * @return self
     */
    public function setMonster($monster)
    {
        if (is_null($monster)) {
            throw new \InvalidArgumentException('non-nullable monster cannot be null');
        }
        $this->container['monster'] = $monster;

        return $this;
    }

    /**
     * Gets schedule
     *
     * @return \ArtifactsMmo\Model\RaidScheduleSchema
     */
    public function getSchedule()
    {
        return $this->container['schedule'];
    }

    /**
     * Sets schedule
     *
     * @param \ArtifactsMmo\Model\RaidScheduleSchema $schedule Weekly raid opening schedule.
     *
     * @return self
     */
    public function setSchedule($schedule)
    {
        if (is_null($schedule)) {
            throw new \InvalidArgumentException('non-nullable schedule cannot be null');
        }
        $this->container['schedule'] = $schedule;

        return $this;
    }

    /**
     * Gets rewards
     *
     * @return \ArtifactsMmo\Model\RaidRewardsSchema|null
     */
    public function getRewards()
    {
        return $this->container['rewards'];
    }

    /**
     * Sets rewards
     *
     * @param \ArtifactsMmo\Model\RaidRewardsSchema|null $rewards Reward rules for the raid.
     *
     * @return self
     */
    public function setRewards($rewards)
    {
        if (is_null($rewards)) {
            throw new \InvalidArgumentException('non-nullable rewards cannot be null');
        }
        $this->container['rewards'] = $rewards;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \ArtifactsMmo\Model\RaidStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \ArtifactsMmo\Model\RaidStatus $status Current overall raid status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets nextStartAt
     *
     * @return \DateTime
     */
    public function getNextStartAt()
    {
        return $this->container['nextStartAt'];
    }

    /**
     * Sets nextStartAt
     *
     * @param \DateTime $nextStartAt Datetime for the next scheduled raid opening in UTC.
     *
     * @return self
     */
    public function setNextStartAt($nextStartAt)
    {
        if (is_null($nextStartAt)) {
            throw new \InvalidArgumentException('non-nullable nextStartAt cannot be null');
        }
        $this->container['nextStartAt'] = $nextStartAt;

        return $this;
    }

    /**
     * Gets participantCount
     *
     * @return int|null
     */
    public function getParticipantCount()
    {
        return $this->container['participantCount'];
    }

    /**
     * Sets participantCount
     *
     * @param int|null $participantCount Number of distinct accounts that contributed to the active or latest raid instance.
     *
     * @return self
     */
    public function setParticipantCount($participantCount)
    {
        if (is_null($participantCount)) {
            throw new \InvalidArgumentException('non-nullable participantCount cannot be null');
        }

        if (($participantCount < 0)) {
            throw new \InvalidArgumentException('invalid value for $participantCount when calling RaidSchema., must be bigger than or equal to 0.');
        }

        $this->container['participantCount'] = $participantCount;

        return $this;
    }

    /**
     * Gets activeInstance
     *
     * @return \ArtifactsMmo\Model\RaidInstanceSchema|null
     */
    public function getActiveInstance()
    {
        return $this->container['activeInstance'];
    }

    /**
     * Sets activeInstance
     *
     * @param \ArtifactsMmo\Model\RaidInstanceSchema|null $activeInstance Currently active weekly raid instance, if any.
     *
     * @return self
     */
    public function setActiveInstance($activeInstance)
    {
        if (is_null($activeInstance)) {
            throw new \InvalidArgumentException('non-nullable activeInstance cannot be null');
        }
        $this->container['activeInstance'] = $activeInstance;

        return $this;
    }

    /**
     * Gets latestInstance
     *
     * @return \ArtifactsMmo\Model\RaidInstanceSchema|null
     */
    public function getLatestInstance()
    {
        return $this->container['latestInstance'];
    }

    /**
     * Sets latestInstance
     *
     * @param \ArtifactsMmo\Model\RaidInstanceSchema|null $latestInstance Latest weekly raid instance, active or finished.
     *
     * @return self
     */
    public function setLatestInstance($latestInstance)
    {
        if (is_null($latestInstance)) {
            throw new \InvalidArgumentException('non-nullable latestInstance cannot be null');
        }
        $this->container['latestInstance'] = $latestInstance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


