<?php
/**
 * GemsShopApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ArtifactsMmo\Test\Api;

use \ArtifactsMmo\Configuration;
use \ArtifactsMmo\ApiException;
use \ArtifactsMmo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GemsShopApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GemsShopApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for buyCustomDesignGemsShopBuyCustomDesignPost
     *
     * Buy Custom Design.
     *
     */
    public function testBuyCustomDesignGemsShopBuyCustomDesignPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for buySkinGemsShopSkinPost
     *
     * Buy Skin.
     *
     */
    public function testBuySkinGemsShopSkinPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for buySpawnEventGemsShopSpawnEventPost
     *
     * Buy Spawn Event.
     *
     */
    public function testBuySpawnEventGemsShopSpawnEventPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for buySubscriptionGemsShopSubscriptionPost
     *
     * Buy Subscription.
     *
     */
    public function testBuySubscriptionGemsShopSubscriptionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogGemsShopGet
     *
     * Get Catalog.
     *
     */
    public function testGetCatalogGemsShopGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
