<?php
/**
 * AccountsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ArtifactsMmo\ApiException;
use ArtifactsMmo\Configuration;
use ArtifactsMmo\FormDataProcessor;
use ArtifactsMmo\HeaderSelector;
use ArtifactsMmo\ObjectSerializer;

/**
 * AccountsApi Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAccountAccountsCreatePost' => [
            'application/json',
        ],
        'forgotPasswordAccountsForgotPasswordPost' => [
            'application/json',
        ],
        'getAccountAccountsAccountGet' => [
            'application/json',
        ],
        'getAccountAchievementsAccountsAccountAchievementsGet' => [
            'application/json',
        ],
        'getAccountCharactersAccountsAccountCharactersGet' => [
            'application/json',
        ],
        'resetPasswordAccountsResetPasswordPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAccountAccountsCreatePost
     *
     * Create Account
     *
     * @param  \ArtifactsMmo\Model\AddAccountSchema $addAccountSchema addAccountSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAccountAccountsCreatePost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\ResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function createAccountAccountsCreatePost($addAccountSchema, string $contentType = self::contentTypes['createAccountAccountsCreatePost'][0])
    {
        list($response) = $this->createAccountAccountsCreatePostWithHttpInfo($addAccountSchema, $contentType);
        return $response;
    }

    /**
     * Operation createAccountAccountsCreatePostWithHttpInfo
     *
     * Create Account
     *
     * @param  \ArtifactsMmo\Model\AddAccountSchema $addAccountSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAccountAccountsCreatePost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\ResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAccountAccountsCreatePostWithHttpInfo($addAccountSchema, string $contentType = self::contentTypes['createAccountAccountsCreatePost'][0])
    {
        $request = $this->createAccountAccountsCreatePostRequest($addAccountSchema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ResponseSchema',
                        $request,
                        $response,
                    );
                case 456:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 457:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\ResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 456:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 457:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createAccountAccountsCreatePostAsync
     *
     * Create Account
     *
     * @param  \ArtifactsMmo\Model\AddAccountSchema $addAccountSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAccountAccountsCreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAccountAccountsCreatePostAsync($addAccountSchema, string $contentType = self::contentTypes['createAccountAccountsCreatePost'][0])
    {
        return $this->createAccountAccountsCreatePostAsyncWithHttpInfo($addAccountSchema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAccountAccountsCreatePostAsyncWithHttpInfo
     *
     * Create Account
     *
     * @param  \ArtifactsMmo\Model\AddAccountSchema $addAccountSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAccountAccountsCreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAccountAccountsCreatePostAsyncWithHttpInfo($addAccountSchema, string $contentType = self::contentTypes['createAccountAccountsCreatePost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\ResponseSchema';
        $request = $this->createAccountAccountsCreatePostRequest($addAccountSchema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAccountAccountsCreatePost'
     *
     * @param  \ArtifactsMmo\Model\AddAccountSchema $addAccountSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAccountAccountsCreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAccountAccountsCreatePostRequest($addAccountSchema, string $contentType = self::contentTypes['createAccountAccountsCreatePost'][0])
    {

        // verify the required parameter 'addAccountSchema' is set
        if ($addAccountSchema === null || (is_array($addAccountSchema) && count($addAccountSchema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $addAccountSchema when calling createAccountAccountsCreatePost'
            );
        }


        $resourcePath = '/accounts/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($addAccountSchema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($addAccountSchema));
            } else {
                $httpBody = $addAccountSchema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation forgotPasswordAccountsForgotPasswordPost
     *
     * Forgot Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetRequestSchema $passwordResetRequestSchema passwordResetRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['forgotPasswordAccountsForgotPasswordPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\PasswordResetResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function forgotPasswordAccountsForgotPasswordPost($passwordResetRequestSchema, string $contentType = self::contentTypes['forgotPasswordAccountsForgotPasswordPost'][0])
    {
        list($response) = $this->forgotPasswordAccountsForgotPasswordPostWithHttpInfo($passwordResetRequestSchema, $contentType);
        return $response;
    }

    /**
     * Operation forgotPasswordAccountsForgotPasswordPostWithHttpInfo
     *
     * Forgot Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetRequestSchema $passwordResetRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['forgotPasswordAccountsForgotPasswordPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\PasswordResetResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function forgotPasswordAccountsForgotPasswordPostWithHttpInfo($passwordResetRequestSchema, string $contentType = self::contentTypes['forgotPasswordAccountsForgotPasswordPost'][0])
    {
        $request = $this->forgotPasswordAccountsForgotPasswordPostRequest($passwordResetRequestSchema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\PasswordResetResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\PasswordResetResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\PasswordResetResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation forgotPasswordAccountsForgotPasswordPostAsync
     *
     * Forgot Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetRequestSchema $passwordResetRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['forgotPasswordAccountsForgotPasswordPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function forgotPasswordAccountsForgotPasswordPostAsync($passwordResetRequestSchema, string $contentType = self::contentTypes['forgotPasswordAccountsForgotPasswordPost'][0])
    {
        return $this->forgotPasswordAccountsForgotPasswordPostAsyncWithHttpInfo($passwordResetRequestSchema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation forgotPasswordAccountsForgotPasswordPostAsyncWithHttpInfo
     *
     * Forgot Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetRequestSchema $passwordResetRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['forgotPasswordAccountsForgotPasswordPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function forgotPasswordAccountsForgotPasswordPostAsyncWithHttpInfo($passwordResetRequestSchema, string $contentType = self::contentTypes['forgotPasswordAccountsForgotPasswordPost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\PasswordResetResponseSchema';
        $request = $this->forgotPasswordAccountsForgotPasswordPostRequest($passwordResetRequestSchema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'forgotPasswordAccountsForgotPasswordPost'
     *
     * @param  \ArtifactsMmo\Model\PasswordResetRequestSchema $passwordResetRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['forgotPasswordAccountsForgotPasswordPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function forgotPasswordAccountsForgotPasswordPostRequest($passwordResetRequestSchema, string $contentType = self::contentTypes['forgotPasswordAccountsForgotPasswordPost'][0])
    {

        // verify the required parameter 'passwordResetRequestSchema' is set
        if ($passwordResetRequestSchema === null || (is_array($passwordResetRequestSchema) && count($passwordResetRequestSchema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $passwordResetRequestSchema when calling forgotPasswordAccountsForgotPasswordPost'
            );
        }


        $resourcePath = '/accounts/forgot_password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($passwordResetRequestSchema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($passwordResetRequestSchema));
            } else {
                $httpBody = $passwordResetRequestSchema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAccountAccountsAccountGet
     *
     * Get Account
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAccountsAccountGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\AccountDetailsSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function getAccountAccountsAccountGet($account, string $contentType = self::contentTypes['getAccountAccountsAccountGet'][0])
    {
        list($response) = $this->getAccountAccountsAccountGetWithHttpInfo($account, $contentType);
        return $response;
    }

    /**
     * Operation getAccountAccountsAccountGetWithHttpInfo
     *
     * Get Account
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAccountsAccountGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\AccountDetailsSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAccountAccountsAccountGetWithHttpInfo($account, string $contentType = self::contentTypes['getAccountAccountsAccountGet'][0])
    {
        $request = $this->getAccountAccountsAccountGetRequest($account, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\AccountDetailsSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\AccountDetailsSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\AccountDetailsSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAccountAccountsAccountGetAsync
     *
     * Get Account
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAccountsAccountGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountAccountsAccountGetAsync($account, string $contentType = self::contentTypes['getAccountAccountsAccountGet'][0])
    {
        return $this->getAccountAccountsAccountGetAsyncWithHttpInfo($account, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAccountAccountsAccountGetAsyncWithHttpInfo
     *
     * Get Account
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAccountsAccountGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountAccountsAccountGetAsyncWithHttpInfo($account, string $contentType = self::contentTypes['getAccountAccountsAccountGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\AccountDetailsSchema';
        $request = $this->getAccountAccountsAccountGetRequest($account, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAccountAccountsAccountGet'
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAccountsAccountGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAccountAccountsAccountGetRequest($account, string $contentType = self::contentTypes['getAccountAccountsAccountGet'][0])
    {

        // verify the required parameter 'account' is set
        if ($account === null || (is_array($account) && count($account) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account when calling getAccountAccountsAccountGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $account)) {
            throw new \InvalidArgumentException("invalid value for \"account\" when calling AccountsApi.getAccountAccountsAccountGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }
        

        $resourcePath = '/accounts/{account}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account !== null) {
            $resourcePath = str_replace(
                '{account}',
                ObjectSerializer::toPathValue($account),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAccountAchievementsAccountsAccountAchievementsGet
     *
     * Get Account Achievements
     *
     * @param  string $account The name of the account. (required)
     * @param  \ArtifactsMmoModelAchievementType|null $type Type of achievements. (optional)
     * @param  bool|null $completed Filter by completed achievements. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\DataPageAccountAchievementSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function getAccountAchievementsAccountsAccountAchievementsGet($account, $type = null, $completed = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'][0])
    {
        list($response) = $this->getAccountAchievementsAccountsAccountAchievementsGetWithHttpInfo($account, $type, $completed, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAccountAchievementsAccountsAccountAchievementsGetWithHttpInfo
     *
     * Get Account Achievements
     *
     * @param  string $account The name of the account. (required)
     * @param  \ArtifactsMmoModelAchievementType|null $type Type of achievements. (optional)
     * @param  bool|null $completed Filter by completed achievements. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\DataPageAccountAchievementSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAccountAchievementsAccountsAccountAchievementsGetWithHttpInfo($account, $type = null, $completed = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'][0])
    {
        $request = $this->getAccountAchievementsAccountsAccountAchievementsGetRequest($account, $type, $completed, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\DataPageAccountAchievementSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\DataPageAccountAchievementSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\DataPageAccountAchievementSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAccountAchievementsAccountsAccountAchievementsGetAsync
     *
     * Get Account Achievements
     *
     * @param  string $account The name of the account. (required)
     * @param  \ArtifactsMmoModelAchievementType|null $type Type of achievements. (optional)
     * @param  bool|null $completed Filter by completed achievements. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountAchievementsAccountsAccountAchievementsGetAsync($account, $type = null, $completed = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'][0])
    {
        return $this->getAccountAchievementsAccountsAccountAchievementsGetAsyncWithHttpInfo($account, $type, $completed, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAccountAchievementsAccountsAccountAchievementsGetAsyncWithHttpInfo
     *
     * Get Account Achievements
     *
     * @param  string $account The name of the account. (required)
     * @param  \ArtifactsMmoModelAchievementType|null $type Type of achievements. (optional)
     * @param  bool|null $completed Filter by completed achievements. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountAchievementsAccountsAccountAchievementsGetAsyncWithHttpInfo($account, $type = null, $completed = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\DataPageAccountAchievementSchema';
        $request = $this->getAccountAchievementsAccountsAccountAchievementsGetRequest($account, $type, $completed, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAccountAchievementsAccountsAccountAchievementsGet'
     *
     * @param  string $account The name of the account. (required)
     * @param  \ArtifactsMmoModelAchievementType|null $type Type of achievements. (optional)
     * @param  bool|null $completed Filter by completed achievements. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAccountAchievementsAccountsAccountAchievementsGetRequest($account, $type = null, $completed = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAccountAchievementsAccountsAccountAchievementsGet'][0])
    {

        // verify the required parameter 'account' is set
        if ($account === null || (is_array($account) && count($account) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account when calling getAccountAchievementsAccountsAccountAchievementsGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $account)) {
            throw new \InvalidArgumentException("invalid value for \"account\" when calling AccountsApi.getAccountAchievementsAccountsAccountAchievementsGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }
        


        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling AccountsApi.getAccountAchievementsAccountsAccountAchievementsGet, must be bigger than or equal to 1.');
        }
        
        if ($size !== null && $size > 100) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling AccountsApi.getAccountAchievementsAccountsAccountAchievementsGet, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling AccountsApi.getAccountAchievementsAccountsAccountAchievementsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/accounts/{account}/achievements';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'AchievementType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $completed,
            'completed', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($account !== null) {
            $resourcePath = str_replace(
                '{account}',
                ObjectSerializer::toPathValue($account),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAccountCharactersAccountsAccountCharactersGet
     *
     * Get Account Characters
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\CharactersListSchema
     */
    public function getAccountCharactersAccountsAccountCharactersGet($account, string $contentType = self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'][0])
    {
        list($response) = $this->getAccountCharactersAccountsAccountCharactersGetWithHttpInfo($account, $contentType);
        return $response;
    }

    /**
     * Operation getAccountCharactersAccountsAccountCharactersGetWithHttpInfo
     *
     * Get Account Characters
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\CharactersListSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAccountCharactersAccountsAccountCharactersGetWithHttpInfo($account, string $contentType = self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'][0])
    {
        $request = $this->getAccountCharactersAccountsAccountCharactersGetRequest($account, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\CharactersListSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\CharactersListSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\CharactersListSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAccountCharactersAccountsAccountCharactersGetAsync
     *
     * Get Account Characters
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountCharactersAccountsAccountCharactersGetAsync($account, string $contentType = self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'][0])
    {
        return $this->getAccountCharactersAccountsAccountCharactersGetAsyncWithHttpInfo($account, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAccountCharactersAccountsAccountCharactersGetAsyncWithHttpInfo
     *
     * Get Account Characters
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccountCharactersAccountsAccountCharactersGetAsyncWithHttpInfo($account, string $contentType = self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\CharactersListSchema';
        $request = $this->getAccountCharactersAccountsAccountCharactersGetRequest($account, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAccountCharactersAccountsAccountCharactersGet'
     *
     * @param  string $account The name of the account. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAccountCharactersAccountsAccountCharactersGetRequest($account, string $contentType = self::contentTypes['getAccountCharactersAccountsAccountCharactersGet'][0])
    {

        // verify the required parameter 'account' is set
        if ($account === null || (is_array($account) && count($account) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account when calling getAccountCharactersAccountsAccountCharactersGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $account)) {
            throw new \InvalidArgumentException("invalid value for \"account\" when calling AccountsApi.getAccountCharactersAccountsAccountCharactersGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }
        

        $resourcePath = '/accounts/{account}/characters';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($account !== null) {
            $resourcePath = str_replace(
                '{account}',
                ObjectSerializer::toPathValue($account),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resetPasswordAccountsResetPasswordPost
     *
     * Reset Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetConfirmSchema $passwordResetConfirmSchema passwordResetConfirmSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resetPasswordAccountsResetPasswordPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\PasswordResetResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function resetPasswordAccountsResetPasswordPost($passwordResetConfirmSchema, string $contentType = self::contentTypes['resetPasswordAccountsResetPasswordPost'][0])
    {
        list($response) = $this->resetPasswordAccountsResetPasswordPostWithHttpInfo($passwordResetConfirmSchema, $contentType);
        return $response;
    }

    /**
     * Operation resetPasswordAccountsResetPasswordPostWithHttpInfo
     *
     * Reset Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetConfirmSchema $passwordResetConfirmSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resetPasswordAccountsResetPasswordPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\PasswordResetResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function resetPasswordAccountsResetPasswordPostWithHttpInfo($passwordResetConfirmSchema, string $contentType = self::contentTypes['resetPasswordAccountsResetPasswordPost'][0])
    {
        $request = $this->resetPasswordAccountsResetPasswordPostRequest($passwordResetConfirmSchema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\PasswordResetResponseSchema',
                        $request,
                        $response,
                    );
                case 561:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 562:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 560:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\PasswordResetResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\PasswordResetResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 561:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 562:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 560:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation resetPasswordAccountsResetPasswordPostAsync
     *
     * Reset Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetConfirmSchema $passwordResetConfirmSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resetPasswordAccountsResetPasswordPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resetPasswordAccountsResetPasswordPostAsync($passwordResetConfirmSchema, string $contentType = self::contentTypes['resetPasswordAccountsResetPasswordPost'][0])
    {
        return $this->resetPasswordAccountsResetPasswordPostAsyncWithHttpInfo($passwordResetConfirmSchema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resetPasswordAccountsResetPasswordPostAsyncWithHttpInfo
     *
     * Reset Password
     *
     * @param  \ArtifactsMmo\Model\PasswordResetConfirmSchema $passwordResetConfirmSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resetPasswordAccountsResetPasswordPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resetPasswordAccountsResetPasswordPostAsyncWithHttpInfo($passwordResetConfirmSchema, string $contentType = self::contentTypes['resetPasswordAccountsResetPasswordPost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\PasswordResetResponseSchema';
        $request = $this->resetPasswordAccountsResetPasswordPostRequest($passwordResetConfirmSchema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resetPasswordAccountsResetPasswordPost'
     *
     * @param  \ArtifactsMmo\Model\PasswordResetConfirmSchema $passwordResetConfirmSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resetPasswordAccountsResetPasswordPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resetPasswordAccountsResetPasswordPostRequest($passwordResetConfirmSchema, string $contentType = self::contentTypes['resetPasswordAccountsResetPasswordPost'][0])
    {

        // verify the required parameter 'passwordResetConfirmSchema' is set
        if ($passwordResetConfirmSchema === null || (is_array($passwordResetConfirmSchema) && count($passwordResetConfirmSchema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $passwordResetConfirmSchema when calling resetPasswordAccountsResetPasswordPost'
            );
        }


        $resourcePath = '/accounts/reset_password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($passwordResetConfirmSchema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($passwordResetConfirmSchema));
            } else {
                $httpBody = $passwordResetConfirmSchema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
