<?php
/**
 * GemsShopApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ArtifactsMmo\ApiException;
use ArtifactsMmo\Configuration;
use ArtifactsMmo\FormDataProcessor;
use ArtifactsMmo\HeaderSelector;
use ArtifactsMmo\ObjectSerializer;

/**
 * GemsShopApi Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GemsShopApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'buyCustomDesignGemsShopBuyCustomDesignPost' => [
            'application/json',
        ],
        'buySkinGemsShopSkinPost' => [
            'application/json',
        ],
        'buySpawnEventGemsShopSpawnEventPost' => [
            'application/json',
        ],
        'buySubscriptionGemsShopSubscriptionPost' => [
            'application/json',
        ],
        'getCatalogGemsShopGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation buyCustomDesignGemsShopBuyCustomDesignPost
     *
     * Buy Custom Design
     *
     * @param  \ArtifactsMmo\Model\BuyCustomDesignRequestSchema $buyCustomDesignRequestSchema buyCustomDesignRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\GemShopCustomDesignPurchaseResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function buyCustomDesignGemsShopBuyCustomDesignPost($buyCustomDesignRequestSchema, string $contentType = self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'][0])
    {
        list($response) = $this->buyCustomDesignGemsShopBuyCustomDesignPostWithHttpInfo($buyCustomDesignRequestSchema, $contentType);
        return $response;
    }

    /**
     * Operation buyCustomDesignGemsShopBuyCustomDesignPostWithHttpInfo
     *
     * Buy Custom Design
     *
     * @param  \ArtifactsMmo\Model\BuyCustomDesignRequestSchema $buyCustomDesignRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\GemShopCustomDesignPurchaseResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function buyCustomDesignGemsShopBuyCustomDesignPostWithHttpInfo($buyCustomDesignRequestSchema, string $contentType = self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'][0])
    {
        $request = $this->buyCustomDesignGemsShopBuyCustomDesignPostRequest($buyCustomDesignRequestSchema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\GemShopCustomDesignPurchaseResponseSchema',
                        $request,
                        $response,
                    );
                case 563:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\GemShopCustomDesignPurchaseResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\GemShopCustomDesignPurchaseResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 563:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation buyCustomDesignGemsShopBuyCustomDesignPostAsync
     *
     * Buy Custom Design
     *
     * @param  \ArtifactsMmo\Model\BuyCustomDesignRequestSchema $buyCustomDesignRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buyCustomDesignGemsShopBuyCustomDesignPostAsync($buyCustomDesignRequestSchema, string $contentType = self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'][0])
    {
        return $this->buyCustomDesignGemsShopBuyCustomDesignPostAsyncWithHttpInfo($buyCustomDesignRequestSchema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation buyCustomDesignGemsShopBuyCustomDesignPostAsyncWithHttpInfo
     *
     * Buy Custom Design
     *
     * @param  \ArtifactsMmo\Model\BuyCustomDesignRequestSchema $buyCustomDesignRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buyCustomDesignGemsShopBuyCustomDesignPostAsyncWithHttpInfo($buyCustomDesignRequestSchema, string $contentType = self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\GemShopCustomDesignPurchaseResponseSchema';
        $request = $this->buyCustomDesignGemsShopBuyCustomDesignPostRequest($buyCustomDesignRequestSchema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'buyCustomDesignGemsShopBuyCustomDesignPost'
     *
     * @param  \ArtifactsMmo\Model\BuyCustomDesignRequestSchema $buyCustomDesignRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function buyCustomDesignGemsShopBuyCustomDesignPostRequest($buyCustomDesignRequestSchema, string $contentType = self::contentTypes['buyCustomDesignGemsShopBuyCustomDesignPost'][0])
    {

        // verify the required parameter 'buyCustomDesignRequestSchema' is set
        if ($buyCustomDesignRequestSchema === null || (is_array($buyCustomDesignRequestSchema) && count($buyCustomDesignRequestSchema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $buyCustomDesignRequestSchema when calling buyCustomDesignGemsShopBuyCustomDesignPost'
            );
        }


        $resourcePath = '/gems_shop/buy_custom_design';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($buyCustomDesignRequestSchema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($buyCustomDesignRequestSchema));
            } else {
                $httpBody = $buyCustomDesignRequestSchema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation buySkinGemsShopSkinPost
     *
     * Buy Skin
     *
     * @param  \ArtifactsMmo\Model\BuySkinRequestSchema $buySkinRequestSchema buySkinRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySkinGemsShopSkinPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\BuySkinResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function buySkinGemsShopSkinPost($buySkinRequestSchema, string $contentType = self::contentTypes['buySkinGemsShopSkinPost'][0])
    {
        list($response) = $this->buySkinGemsShopSkinPostWithHttpInfo($buySkinRequestSchema, $contentType);
        return $response;
    }

    /**
     * Operation buySkinGemsShopSkinPostWithHttpInfo
     *
     * Buy Skin
     *
     * @param  \ArtifactsMmo\Model\BuySkinRequestSchema $buySkinRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySkinGemsShopSkinPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\BuySkinResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function buySkinGemsShopSkinPostWithHttpInfo($buySkinRequestSchema, string $contentType = self::contentTypes['buySkinGemsShopSkinPost'][0])
    {
        $request = $this->buySkinGemsShopSkinPostRequest($buySkinRequestSchema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\BuySkinResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 551:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 552:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 563:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\BuySkinResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\BuySkinResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 551:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 552:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 563:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation buySkinGemsShopSkinPostAsync
     *
     * Buy Skin
     *
     * @param  \ArtifactsMmo\Model\BuySkinRequestSchema $buySkinRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySkinGemsShopSkinPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buySkinGemsShopSkinPostAsync($buySkinRequestSchema, string $contentType = self::contentTypes['buySkinGemsShopSkinPost'][0])
    {
        return $this->buySkinGemsShopSkinPostAsyncWithHttpInfo($buySkinRequestSchema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation buySkinGemsShopSkinPostAsyncWithHttpInfo
     *
     * Buy Skin
     *
     * @param  \ArtifactsMmo\Model\BuySkinRequestSchema $buySkinRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySkinGemsShopSkinPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buySkinGemsShopSkinPostAsyncWithHttpInfo($buySkinRequestSchema, string $contentType = self::contentTypes['buySkinGemsShopSkinPost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\BuySkinResponseSchema';
        $request = $this->buySkinGemsShopSkinPostRequest($buySkinRequestSchema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'buySkinGemsShopSkinPost'
     *
     * @param  \ArtifactsMmo\Model\BuySkinRequestSchema $buySkinRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySkinGemsShopSkinPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function buySkinGemsShopSkinPostRequest($buySkinRequestSchema, string $contentType = self::contentTypes['buySkinGemsShopSkinPost'][0])
    {

        // verify the required parameter 'buySkinRequestSchema' is set
        if ($buySkinRequestSchema === null || (is_array($buySkinRequestSchema) && count($buySkinRequestSchema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $buySkinRequestSchema when calling buySkinGemsShopSkinPost'
            );
        }


        $resourcePath = '/gems_shop/skin';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($buySkinRequestSchema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($buySkinRequestSchema));
            } else {
                $httpBody = $buySkinRequestSchema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation buySpawnEventGemsShopSpawnEventPost
     *
     * Buy Spawn Event
     *
     * @param  \ArtifactsMmo\Model\SpawnEventRequestSchema $spawnEventRequestSchema spawnEventRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySpawnEventGemsShopSpawnEventPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\ActiveEventResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function buySpawnEventGemsShopSpawnEventPost($spawnEventRequestSchema, string $contentType = self::contentTypes['buySpawnEventGemsShopSpawnEventPost'][0])
    {
        list($response) = $this->buySpawnEventGemsShopSpawnEventPostWithHttpInfo($spawnEventRequestSchema, $contentType);
        return $response;
    }

    /**
     * Operation buySpawnEventGemsShopSpawnEventPostWithHttpInfo
     *
     * Buy Spawn Event
     *
     * @param  \ArtifactsMmo\Model\SpawnEventRequestSchema $spawnEventRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySpawnEventGemsShopSpawnEventPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\ActiveEventResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function buySpawnEventGemsShopSpawnEventPostWithHttpInfo($spawnEventRequestSchema, string $contentType = self::contentTypes['buySpawnEventGemsShopSpawnEventPost'][0])
    {
        $request = $this->buySpawnEventGemsShopSpawnEventPostRequest($spawnEventRequestSchema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ActiveEventResponseSchema',
                        $request,
                        $response,
                    );
                case 563:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 564:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 566:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 571:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\ActiveEventResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ActiveEventResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 563:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 564:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 566:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 571:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation buySpawnEventGemsShopSpawnEventPostAsync
     *
     * Buy Spawn Event
     *
     * @param  \ArtifactsMmo\Model\SpawnEventRequestSchema $spawnEventRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySpawnEventGemsShopSpawnEventPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buySpawnEventGemsShopSpawnEventPostAsync($spawnEventRequestSchema, string $contentType = self::contentTypes['buySpawnEventGemsShopSpawnEventPost'][0])
    {
        return $this->buySpawnEventGemsShopSpawnEventPostAsyncWithHttpInfo($spawnEventRequestSchema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation buySpawnEventGemsShopSpawnEventPostAsyncWithHttpInfo
     *
     * Buy Spawn Event
     *
     * @param  \ArtifactsMmo\Model\SpawnEventRequestSchema $spawnEventRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySpawnEventGemsShopSpawnEventPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buySpawnEventGemsShopSpawnEventPostAsyncWithHttpInfo($spawnEventRequestSchema, string $contentType = self::contentTypes['buySpawnEventGemsShopSpawnEventPost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\ActiveEventResponseSchema';
        $request = $this->buySpawnEventGemsShopSpawnEventPostRequest($spawnEventRequestSchema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'buySpawnEventGemsShopSpawnEventPost'
     *
     * @param  \ArtifactsMmo\Model\SpawnEventRequestSchema $spawnEventRequestSchema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySpawnEventGemsShopSpawnEventPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function buySpawnEventGemsShopSpawnEventPostRequest($spawnEventRequestSchema, string $contentType = self::contentTypes['buySpawnEventGemsShopSpawnEventPost'][0])
    {

        // verify the required parameter 'spawnEventRequestSchema' is set
        if ($spawnEventRequestSchema === null || (is_array($spawnEventRequestSchema) && count($spawnEventRequestSchema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $spawnEventRequestSchema when calling buySpawnEventGemsShopSpawnEventPost'
            );
        }


        $resourcePath = '/gems_shop/spawn_event';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($spawnEventRequestSchema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($spawnEventRequestSchema));
            } else {
                $httpBody = $spawnEventRequestSchema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation buySubscriptionGemsShopSubscriptionPost
     *
     * Buy Subscription
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySubscriptionGemsShopSubscriptionPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\GemShopSubscriptionResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function buySubscriptionGemsShopSubscriptionPost(string $contentType = self::contentTypes['buySubscriptionGemsShopSubscriptionPost'][0])
    {
        list($response) = $this->buySubscriptionGemsShopSubscriptionPostWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation buySubscriptionGemsShopSubscriptionPostWithHttpInfo
     *
     * Buy Subscription
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySubscriptionGemsShopSubscriptionPost'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\GemShopSubscriptionResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function buySubscriptionGemsShopSubscriptionPostWithHttpInfo(string $contentType = self::contentTypes['buySubscriptionGemsShopSubscriptionPost'][0])
    {
        $request = $this->buySubscriptionGemsShopSubscriptionPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\GemShopSubscriptionResponseSchema',
                        $request,
                        $response,
                    );
                case 563:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 573:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\GemShopSubscriptionResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\GemShopSubscriptionResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 563:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 573:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation buySubscriptionGemsShopSubscriptionPostAsync
     *
     * Buy Subscription
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySubscriptionGemsShopSubscriptionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buySubscriptionGemsShopSubscriptionPostAsync(string $contentType = self::contentTypes['buySubscriptionGemsShopSubscriptionPost'][0])
    {
        return $this->buySubscriptionGemsShopSubscriptionPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation buySubscriptionGemsShopSubscriptionPostAsyncWithHttpInfo
     *
     * Buy Subscription
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySubscriptionGemsShopSubscriptionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function buySubscriptionGemsShopSubscriptionPostAsyncWithHttpInfo(string $contentType = self::contentTypes['buySubscriptionGemsShopSubscriptionPost'][0])
    {
        $returnType = '\ArtifactsMmo\Model\GemShopSubscriptionResponseSchema';
        $request = $this->buySubscriptionGemsShopSubscriptionPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'buySubscriptionGemsShopSubscriptionPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['buySubscriptionGemsShopSubscriptionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function buySubscriptionGemsShopSubscriptionPostRequest(string $contentType = self::contentTypes['buySubscriptionGemsShopSubscriptionPost'][0])
    {


        $resourcePath = '/gems_shop/subscription';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCatalogGemsShopGet
     *
     * Get Catalog
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogGemsShopGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\GemShopCatalogResponseSchema
     */
    public function getCatalogGemsShopGet(string $contentType = self::contentTypes['getCatalogGemsShopGet'][0])
    {
        list($response) = $this->getCatalogGemsShopGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getCatalogGemsShopGetWithHttpInfo
     *
     * Get Catalog
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogGemsShopGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\GemShopCatalogResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCatalogGemsShopGetWithHttpInfo(string $contentType = self::contentTypes['getCatalogGemsShopGet'][0])
    {
        $request = $this->getCatalogGemsShopGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\GemShopCatalogResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\GemShopCatalogResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\GemShopCatalogResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCatalogGemsShopGetAsync
     *
     * Get Catalog
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogGemsShopGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogGemsShopGetAsync(string $contentType = self::contentTypes['getCatalogGemsShopGet'][0])
    {
        return $this->getCatalogGemsShopGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCatalogGemsShopGetAsyncWithHttpInfo
     *
     * Get Catalog
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogGemsShopGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCatalogGemsShopGetAsyncWithHttpInfo(string $contentType = self::contentTypes['getCatalogGemsShopGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\GemShopCatalogResponseSchema';
        $request = $this->getCatalogGemsShopGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCatalogGemsShopGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCatalogGemsShopGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCatalogGemsShopGetRequest(string $contentType = self::contentTypes['getCatalogGemsShopGet'][0])
    {


        $resourcePath = '/gems_shop/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
