<?php
/**
 * TasksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 8.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ArtifactsMmo\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ArtifactsMmo\ApiException;
use ArtifactsMmo\Configuration;
use ArtifactsMmo\FormDataProcessor;
use ArtifactsMmo\HeaderSelector;
use ArtifactsMmo\ObjectSerializer;

/**
 * TasksApi Class Doc Comment
 *
 * @category Class
 * @package  ArtifactsMmo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TasksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllTasksRewardsTasksRewardsGet' => [
            'application/json',
        ],
        'getAllTasksTasksListGet' => [
            'application/json',
        ],
        'getTaskTasksListCodeGet' => [
            'application/json',
        ],
        'getTasksRewardTasksRewardsCodeGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllTasksRewardsTasksRewardsGet
     *
     * Get All Tasks Rewards
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksRewardsTasksRewardsGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\StaticDataPageDropRateSchema
     */
    public function getAllTasksRewardsTasksRewardsGet($page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksRewardsTasksRewardsGet'][0])
    {
        list($response) = $this->getAllTasksRewardsTasksRewardsGetWithHttpInfo($page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAllTasksRewardsTasksRewardsGetWithHttpInfo
     *
     * Get All Tasks Rewards
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksRewardsTasksRewardsGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\StaticDataPageDropRateSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllTasksRewardsTasksRewardsGetWithHttpInfo($page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksRewardsTasksRewardsGet'][0])
    {
        $request = $this->getAllTasksRewardsTasksRewardsGetRequest($page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\StaticDataPageDropRateSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\StaticDataPageDropRateSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\StaticDataPageDropRateSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAllTasksRewardsTasksRewardsGetAsync
     *
     * Get All Tasks Rewards
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksRewardsTasksRewardsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllTasksRewardsTasksRewardsGetAsync($page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksRewardsTasksRewardsGet'][0])
    {
        return $this->getAllTasksRewardsTasksRewardsGetAsyncWithHttpInfo($page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllTasksRewardsTasksRewardsGetAsyncWithHttpInfo
     *
     * Get All Tasks Rewards
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksRewardsTasksRewardsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllTasksRewardsTasksRewardsGetAsyncWithHttpInfo($page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksRewardsTasksRewardsGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\StaticDataPageDropRateSchema';
        $request = $this->getAllTasksRewardsTasksRewardsGetRequest($page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllTasksRewardsTasksRewardsGet'
     *
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksRewardsTasksRewardsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllTasksRewardsTasksRewardsGetRequest($page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksRewardsTasksRewardsGet'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling TasksApi.getAllTasksRewardsTasksRewardsGet, must be bigger than or equal to 1.');
        }
        
        if ($size !== null && $size > 10000) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling TasksApi.getAllTasksRewardsTasksRewardsGet, must be smaller than or equal to 10000.');
        }
        if ($size !== null && $size < 1) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling TasksApi.getAllTasksRewardsTasksRewardsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/tasks/rewards';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllTasksTasksListGet
     *
     * Get All Tasks
     *
     * @param  int|null $minLevel Minimum level. (optional)
     * @param  int|null $maxLevel Maximum level. (optional)
     * @param  \ArtifactsMmoModelSkill|null $skill Skill of tasks. (optional)
     * @param  \ArtifactsMmoModelTaskType|null $type Type of tasks. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksTasksListGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\StaticDataPageTaskFullSchema
     */
    public function getAllTasksTasksListGet($minLevel = null, $maxLevel = null, $skill = null, $type = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksTasksListGet'][0])
    {
        list($response) = $this->getAllTasksTasksListGetWithHttpInfo($minLevel, $maxLevel, $skill, $type, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getAllTasksTasksListGetWithHttpInfo
     *
     * Get All Tasks
     *
     * @param  int|null $minLevel Minimum level. (optional)
     * @param  int|null $maxLevel Maximum level. (optional)
     * @param  \ArtifactsMmoModelSkill|null $skill Skill of tasks. (optional)
     * @param  \ArtifactsMmoModelTaskType|null $type Type of tasks. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksTasksListGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\StaticDataPageTaskFullSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllTasksTasksListGetWithHttpInfo($minLevel = null, $maxLevel = null, $skill = null, $type = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksTasksListGet'][0])
    {
        $request = $this->getAllTasksTasksListGetRequest($minLevel, $maxLevel, $skill, $type, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\StaticDataPageTaskFullSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\StaticDataPageTaskFullSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\StaticDataPageTaskFullSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAllTasksTasksListGetAsync
     *
     * Get All Tasks
     *
     * @param  int|null $minLevel Minimum level. (optional)
     * @param  int|null $maxLevel Maximum level. (optional)
     * @param  \ArtifactsMmoModelSkill|null $skill Skill of tasks. (optional)
     * @param  \ArtifactsMmoModelTaskType|null $type Type of tasks. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksTasksListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllTasksTasksListGetAsync($minLevel = null, $maxLevel = null, $skill = null, $type = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksTasksListGet'][0])
    {
        return $this->getAllTasksTasksListGetAsyncWithHttpInfo($minLevel, $maxLevel, $skill, $type, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllTasksTasksListGetAsyncWithHttpInfo
     *
     * Get All Tasks
     *
     * @param  int|null $minLevel Minimum level. (optional)
     * @param  int|null $maxLevel Maximum level. (optional)
     * @param  \ArtifactsMmoModelSkill|null $skill Skill of tasks. (optional)
     * @param  \ArtifactsMmoModelTaskType|null $type Type of tasks. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksTasksListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllTasksTasksListGetAsyncWithHttpInfo($minLevel = null, $maxLevel = null, $skill = null, $type = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksTasksListGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\StaticDataPageTaskFullSchema';
        $request = $this->getAllTasksTasksListGetRequest($minLevel, $maxLevel, $skill, $type, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllTasksTasksListGet'
     *
     * @param  int|null $minLevel Minimum level. (optional)
     * @param  int|null $maxLevel Maximum level. (optional)
     * @param  \ArtifactsMmoModelSkill|null $skill Skill of tasks. (optional)
     * @param  \ArtifactsMmoModelTaskType|null $type Type of tasks. (optional)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  int|null $size Page size (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllTasksTasksListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllTasksTasksListGetRequest($minLevel = null, $maxLevel = null, $skill = null, $type = null, $page = 1, $size = 50, string $contentType = self::contentTypes['getAllTasksTasksListGet'][0])
    {

        if ($minLevel !== null && $minLevel < 0) {
            throw new \InvalidArgumentException('invalid value for "$minLevel" when calling TasksApi.getAllTasksTasksListGet, must be bigger than or equal to 0.');
        }
        
        if ($maxLevel !== null && $maxLevel < 0) {
            throw new \InvalidArgumentException('invalid value for "$maxLevel" when calling TasksApi.getAllTasksTasksListGet, must be bigger than or equal to 0.');
        }
        


        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling TasksApi.getAllTasksTasksListGet, must be bigger than or equal to 1.');
        }
        
        if ($size !== null && $size > 10000) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling TasksApi.getAllTasksTasksListGet, must be smaller than or equal to 10000.');
        }
        if ($size !== null && $size < 1) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling TasksApi.getAllTasksTasksListGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/tasks/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $minLevel,
            'min_level', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $maxLevel,
            'max_level', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skill,
            'skill', // param base name
            'Skill', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'TaskType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTaskTasksListCodeGet
     *
     * Get Task
     *
     * @param  string $code The code of the task. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTaskTasksListCodeGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\TaskFullResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function getTaskTasksListCodeGet($code, string $contentType = self::contentTypes['getTaskTasksListCodeGet'][0])
    {
        list($response) = $this->getTaskTasksListCodeGetWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation getTaskTasksListCodeGetWithHttpInfo
     *
     * Get Task
     *
     * @param  string $code The code of the task. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTaskTasksListCodeGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\TaskFullResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTaskTasksListCodeGetWithHttpInfo($code, string $contentType = self::contentTypes['getTaskTasksListCodeGet'][0])
    {
        $request = $this->getTaskTasksListCodeGetRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\TaskFullResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\TaskFullResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\TaskFullResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTaskTasksListCodeGetAsync
     *
     * Get Task
     *
     * @param  string $code The code of the task. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTaskTasksListCodeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTaskTasksListCodeGetAsync($code, string $contentType = self::contentTypes['getTaskTasksListCodeGet'][0])
    {
        return $this->getTaskTasksListCodeGetAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTaskTasksListCodeGetAsyncWithHttpInfo
     *
     * Get Task
     *
     * @param  string $code The code of the task. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTaskTasksListCodeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTaskTasksListCodeGetAsyncWithHttpInfo($code, string $contentType = self::contentTypes['getTaskTasksListCodeGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\TaskFullResponseSchema';
        $request = $this->getTaskTasksListCodeGetRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTaskTasksListCodeGet'
     *
     * @param  string $code The code of the task. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTaskTasksListCodeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTaskTasksListCodeGetRequest($code, string $contentType = self::contentTypes['getTaskTasksListCodeGet'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getTaskTasksListCodeGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $code)) {
            throw new \InvalidArgumentException("invalid value for \"code\" when calling TasksApi.getTaskTasksListCodeGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }
        

        $resourcePath = '/tasks/list/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{code}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTasksRewardTasksRewardsCodeGet
     *
     * Get Tasks Reward
     *
     * @param  string $code The code of the tasks reward. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTasksRewardTasksRewardsCodeGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ArtifactsMmo\Model\RewardResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema
     */
    public function getTasksRewardTasksRewardsCodeGet($code, string $contentType = self::contentTypes['getTasksRewardTasksRewardsCodeGet'][0])
    {
        list($response) = $this->getTasksRewardTasksRewardsCodeGetWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation getTasksRewardTasksRewardsCodeGetWithHttpInfo
     *
     * Get Tasks Reward
     *
     * @param  string $code The code of the tasks reward. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTasksRewardTasksRewardsCodeGet'] to see the possible values for this operation
     *
     * @throws \ArtifactsMmo\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ArtifactsMmo\Model\RewardResponseSchema|\ArtifactsMmo\Model\ErrorResponseSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTasksRewardTasksRewardsCodeGetWithHttpInfo($code, string $contentType = self::contentTypes['getTasksRewardTasksRewardsCodeGet'][0])
    {
        $request = $this->getTasksRewardTasksRewardsCodeGetRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\RewardResponseSchema',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ArtifactsMmo\Model\RewardResponseSchema',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\RewardResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ArtifactsMmo\Model\ErrorResponseSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTasksRewardTasksRewardsCodeGetAsync
     *
     * Get Tasks Reward
     *
     * @param  string $code The code of the tasks reward. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTasksRewardTasksRewardsCodeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTasksRewardTasksRewardsCodeGetAsync($code, string $contentType = self::contentTypes['getTasksRewardTasksRewardsCodeGet'][0])
    {
        return $this->getTasksRewardTasksRewardsCodeGetAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTasksRewardTasksRewardsCodeGetAsyncWithHttpInfo
     *
     * Get Tasks Reward
     *
     * @param  string $code The code of the tasks reward. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTasksRewardTasksRewardsCodeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTasksRewardTasksRewardsCodeGetAsyncWithHttpInfo($code, string $contentType = self::contentTypes['getTasksRewardTasksRewardsCodeGet'][0])
    {
        $returnType = '\ArtifactsMmo\Model\RewardResponseSchema';
        $request = $this->getTasksRewardTasksRewardsCodeGetRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTasksRewardTasksRewardsCodeGet'
     *
     * @param  string $code The code of the tasks reward. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTasksRewardTasksRewardsCodeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTasksRewardTasksRewardsCodeGetRequest($code, string $contentType = self::contentTypes['getTasksRewardTasksRewardsCodeGet'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getTasksRewardTasksRewardsCodeGet'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]+$/", $code)) {
            throw new \InvalidArgumentException("invalid value for \"code\" when calling TasksApi.getTasksRewardTasksRewardsCodeGet, must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }
        

        $resourcePath = '/tasks/rewards/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{code}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
